language: node_js # 设置语言
node_js: stable # 设置相应版本

install:
    - npm install # 安装hexo及插件
    - npm install 

cache:
  directories:
    - node_modules

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install node-sass@latest
  - cnpm install hexo-cli -g


script:
    - hexo clean # 清除
    - hexo g # 生成

after_script: #记得将theme下面的.git文件删除掉，要不然部署会出现layout错误
    - cd ./public
    - git init
    - git config user.name "WenDeng" # 修改name
    - git config user.email "201722060935@std.uestc.edu.cn" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称

branches:
    only:
        - hexo-source  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com/WenDeng/WenDeng.github.io.git #设置GH_REF，注意更改yourname
